### ISSUE TITLE
Export crashes with java.lang.IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by xunto** [MattiBorchers/MinecraftEarthMap#13]
Export crashes with following error:
```java
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
WorldPainter scripting host version 2.7.3.
Copyright 2011-2019 pepsoft.org, The Netherlands.
This is free software distributed under the terms of the GPL, version 3, a copy
of which you can find in the installation directory.

Executing script "export.js" with arguments "./v38.world"

[ERROR] RuntimeException while exporting region 12,15
java.lang.RuntimeException: Comparison method violates its general contract! (region: java.awt.Point[x=12,y=15])
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.exportRegion(AbstractWorldExporter.java:765)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.lambda$parallelExportRegions$0(AbstractWorldExporter.java:275)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:744)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:481)
	at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:406)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
	at java.util.Arrays.sort(Arrays.java:1312)
	at java.util.Arrays.sort(Arrays.java:1506)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at java.util.Collections.sort(Collections.java:141)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.exportRegion(AbstractWorldExporter.java:694)
	... 4 common frames omitted
[ERROR] RuntimeException occurred while executing export.js
java.lang.RuntimeException: RuntimeException while exporting region12,15
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.lambda$parallelExportRegions$0(AbstractWorldExporter.java:308)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The world is so big (10000x10000) with lots of custom layers, so I had to export from plain console using wpscript and thoese vm settings:
```
# Enter one VM parameter per line
# For example, to adjust the maximum memory usage to 512 MB, uncomment the following line:
# -Xmx512m
# To include another file, uncomment the following line:
# -include-options [path to other .vmoption file]
-Xmx28G
-XX:+UseConcMarkSweepGC
-XX:+CMSIncrementalMode
#-XX:+PrintGCDetails
#-XX:+PrintGCTimeStamps
```

I may provide world file but I don't want to do it publicly (as I use it for project where it's important for players not to know what map looks like) and it weights a lot.

**Comment by xunto** [comment]
Sorry! Wrong project!
